### ISSUE TITLE
일반 회원가입

### ISSUE THREAD

**Issue by jjunnnys** [dnd-mentee-3rd/dnd-mentee-3rd-6-repo#10]
- API 명세: http://15.164.158.155/docs/api-guide.html , #50 참고

**Comment by chaeyun17** [comment]
백엔드 
회원가입 API

**Comment by jjunnnys** [comment]
# FE
- 회원가입 UI 폼 만들기

**Comment by jjunnnys** [comment]
# 컴포넌트 구조 (변경될 수 있음 - 08/16)
- 회원가입 페이지(auth)
## 총 5단계
1. SignUp - 유저 기본 정보 등록
2. ProfileImage - 프로필 이미지 등록
3. Kinds - 품종 목록
4. Cats - 냥이 등록
5. Address - 주소지 검색, 집사 닉네임, 주소지 등록

**Comment by chaeyun17** [comment]
현재까지 개발된 API 문서

http://15.164.158.155/swagger-ui.html
