### ISSUE TITLE
회원가입 파라미터 타입 버그

### ISSUE THREAD

**Issue by chaeyun17** [dnd-mentee-3rd/dnd-mentee-3rd-6-repo#132]
## 문제
- 서버에서 catKindId를 NULL 로 파싱하지 못하고, String 으로 "null"로 파싱됨.

## 원인추정
- json 형식에서는 value 값을 null 로하면 NULL 로 파싱을 하지만, form-data 형식에서는 null을 string으로 파싱하는 것 같음.

## 시도
- postman을 통해 catKindId를 숫자 0 또는 공란으로 요청을 해보니, 성공적으로 등록됨.

## 버그 해결 방법
- 프론트엔드에서 catKindId를 숫자 0 또는 공란으로 파라미터 값으로 세팅하기.
## 문제 참고 자료

![image.png](https://images.zenhubusercontent.com/5f2555f736bda7811178682b/664afce8-2b71-4e39-ac88-70cc5b9d873d)
![image.png](https://images.zenhubusercontent.com/5f2555f736bda7811178682b/5339c3ca-a600-41d1-a1f4-a7013ae88f0b)
![image](https://user-images.githubusercontent.com/24735860/92422599-ec5cc280-f1b8-11ea-989b-dfcc33e297be.png)

**Comment by jjunnnys** [comment]
혹시 catProfileImg는 null인데 괜찮나요?
