### ISSUE TITLE
동네인증-지도 화면 로딩 안됨.

### ISSUE THREAD

**Issue by chaeyun17** [dnd-mentee-3rd/dnd-mentee-3rd-6-repo#133]
## 문제
- 동네 인증 카카오맵 화면이 표시되지 않음.
- 401 UnAuthorized 응답 HTTP 코드. 
- 동네 인증 지도 화면 이동하면 현재 위치 주소는 정상적으로 뜸

![image.png](https://images.zenhubusercontent.com/5f2555f736bda7811178682b/d58951b4-381d-4085-bfb0-a2af056d9100)
![image.png](https://images.zenhubusercontent.com/5f2555f736bda7811178682b/3f7db606-1921-448b-92aa-a27b5f9b64fe)

## 문제 추정
- API 키 확인 필요

## 시도
- 아직 안해 봄

**Comment by jjunnnys** [comment]
카카오맵 사이트 도메인 등록 완료

**Comment by jjunnnys** [comment]
마커 위치 수정 필요
