### ISSUE TITLE
파이어베이스 인증번호 에러

### ISSUE THREAD

**Issue by jjunnnys** [dnd-mentee-3rd/dnd-mentee-3rd-6-repo#138]
# 문제
- 기존에 테스트로 등록했던 번호로만 인증번호가 날라온다

# 원인 추측
- 도메인을 연결 시켜줘야 하는 거 같음
<img width="778" alt="스크린샷 2020-09-08 오후 2 26 02" src="https://user-images.githubusercontent.com/57027805/92436787-753b2480-f1e0-11ea-884d-cc344de7e084.png">
- 로컬 환경에서는 테스트로 등록했던 걸 지우고 요청해도 메세지가 잘 날라옴

**Comment by chaeyun17** [comment]
파이어베이스에 등록된 계정들 삭제하고 한 번 테스트해보시는 것도 좋을 것 같습니다 ㅎㅎ
