### ISSUE TITLE
reCAPTCHA 리캡차 표시 버그

### ISSUE THREAD

**Issue by chaeyun17** [dnd-mentee-3rd/dnd-mentee-3rd-6-repo#77]
## 문제상황
- 회원가입에서 번호 인증 시, 리캡차 선택 창이 뜸.

<img width="146" alt="스크린샷 2020-08-26 오후 9 52 55" src="https://user-images.githubusercontent.com/24735860/91382774-6b6f0400-e865-11ea-9585-ebe8d2a75ada.png">

## 원인 추정
- Firebase 리캡챠 설정 문제. 리캡챠 안보이도록 하는 설정이 잘 안되어있을 가능성. Firebase 공식문서 상, 리캡차 안보이게 자동으로 할 수 있도록 지원함. React 에 기능을 추가하는 부분을 다시 보기.

## 시도
- 리캡차 소스코드 다시 점검.
- 리캡차+리액트 테스트 프로젝트를 만들어서 리캡차 기능 테스트 해보기

**Comment by jjunnnys** [comment]
https://stackoverrun.com/ko/q/13075663
